version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_lor:/var/lib/postgresql/data
    restart: "no"

volumes:
  db_lor:
    driver: local
