version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_lor:/var/lib/postgresql/data
    restart: "no"

  minio:
    image: minio/minio:RELEASE.2024-01-31T20-20-33Z
    ports:
      - "9001:9000"
      - "9090:9090"
    volumes:
      - s3_lor:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
    command: server --console-address ":9090" /data
    restart: "no"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint:
      - /bin/sh
      - -c
      - |
        mc alias set minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
        mc mb minio/replays;
        mc mb minio/pictures;
        mc mb minio/original;
        mc anonymous set download minio/replays;
        mc anonymous set download minio/pictures;
        mc admin user add minio ${S3_ACCESS_KEY} ${S3_SECRET_KEY};
        mc admin policy attach minio readwrite --user ${S3_ACCESS_KEY};
        exit 0;

volumes:
  db_lor:
    driver: local
  s3_lor: {}
