version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_lor:/var/lib/postgresql/data
    restart: "no"

  minio:
    image: minio/minio:RELEASE.2023-11-20T22-40-07Z
    ports:
      - "9001:9000"
      - "9090:9090"
    volumes:
      - s3_lor:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: toortoor
    command: server --console-address ":9090" /data
    restart: "no"


volumes:
  db_lor:
    driver: local
  s3_lor: {}
