import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :lor, LorWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Lor.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# replays schedulers
config :lor,
  replay_schedulers: %{
    featured: %{
      active?: false,
      platform_ids: [:kr]
    },
    pro: %{
      active?: false,
      platform_ids: [:kr]
    }
  }
