defmodule Lor.Repo.Migrations.UpdateReplays do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lol_replays) do
      remove :status
      add :first_chunk_id, :smallint
      add :first_key_frame_id, :smallint
      add :last_chunk_id, :smallint
      add :last_key_frame_id, :smallint
      add :state, :text, null: false, default: "recording"
    end
  end

  def down do
    alter table(:lol_replays) do
      remove :state
      remove :last_key_frame_id
      remove :last_chunk_id
      remove :first_key_frame_id
      remove :first_chunk_id
      add :status, :text, null: false, default: "recording"
    end
  end
end
