defmodule Lor.Repo.Migrations.UpdateSummonersSetNullableName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lol_summoners) do
      modify :name, :text, null: true
    end
  end

  def down do
    alter table(:lol_summoners) do
      modify :name, :text, null: false
    end
  end
end
