defmodule Lor.Repo.Migrations.UpdateReplaysAddMatchId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lol_replays) do
      add :match_id,
          references(:lol_matches,
            column: :id,
            name: "lol_replays_match_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:lol_replays, "lol_replays_match_id_fkey")

    alter table(:lol_replays) do
      remove :match_id
    end
  end
end
