defmodule Lor.Repo.Migrations.UpdateMatchAddGameStart do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lol_matches) do
      add :game_start, :utc_datetime, null: false
    end
  end

  def down do
    alter table(:lol_matches) do
      remove :game_start
    end
  end
end