defmodule Lor.Repo.Migrations.UpdateTeamsLogoReference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:pro_teams, "pro_teams_logo_id_fkey")

    alter table(:pro_teams) do
      modify :logo_id,
             references(:s3_objects,
               column: :id,
               name: "pro_teams_logo_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing
             )
    end

    execute("ALTER TABLE pro_teams alter CONSTRAINT pro_teams_logo_id_fkey NOT DEFERRABLE")
  end

  def down do
    drop constraint(:pro_teams, "pro_teams_logo_id_fkey")

    alter table(:pro_teams) do
      modify :logo_id,
             references(:s3_objects,
               column: :id,
               name: "pro_teams_logo_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end
end
