defmodule Lor.Repo.Migrations.UpdateModelsOnDelete do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:pro_teams, "pro_teams_logo_id_fkey")

    alter table(:pro_teams) do
      modify :logo_id,
             references(:s3_objects,
               column: :id,
               name: "pro_teams_logo_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:pro_players, "pro_players_picture_id_fkey")

    drop constraint(:pro_players, "pro_players_current_team_id_fkey")

    alter table(:pro_players) do
      modify :current_team_id,
             references(:pro_teams,
               column: :id,
               name: "pro_players_current_team_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    drop constraint(:lol_summoners, "lol_summoners_player_id_fkey")

    alter table(:lol_summoners) do
      modify :player_id,
             references(:pro_players,
               column: :id,
               name: "lol_summoners_player_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    execute(
      "ALTER TABLE lol_summoners alter CONSTRAINT lol_summoners_player_id_fkey NOT DEFERRABLE"
    )

    execute(
      "ALTER TABLE pro_players alter CONSTRAINT pro_players_current_team_id_fkey NOT DEFERRABLE"
    )

    alter table(:pro_players) do
      modify :picture_id,
             references(:s3_objects,
               column: :id,
               name: "pro_players_picture_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    execute("ALTER TABLE pro_players alter CONSTRAINT pro_players_picture_id_fkey NOT DEFERRABLE")

    execute("ALTER TABLE pro_teams alter CONSTRAINT pro_teams_logo_id_fkey NOT DEFERRABLE")
  end

  def down do
    drop constraint(:pro_players, "pro_players_picture_id_fkey")

    alter table(:pro_players) do
      modify :picture_id,
             references(:s3_objects,
               column: :id,
               name: "pro_players_picture_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:lol_summoners, "lol_summoners_player_id_fkey")

    alter table(:lol_summoners) do
      modify :player_id,
             references(:pro_players,
               column: :id,
               name: "lol_summoners_player_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:pro_players, "pro_players_current_team_id_fkey")

    alter table(:pro_players) do
      modify :current_team_id,
             references(:pro_teams,
               column: :id,
               name: "pro_players_current_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:pro_teams, "pro_teams_logo_id_fkey")

    alter table(:pro_teams) do
      modify :logo_id,
             references(:s3_objects,
               column: :id,
               name: "pro_teams_logo_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
