defmodule Lor.Repo.Migrations.CreateLolActiveGames do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:lol_active_games, primary_key: false) do
      add :id, :text, null: false, primary_key: true
      add :platform_id, :text, null: false
      add :game_id, :bigint, null: false
      add :game_mode, :text, null: false
      add :game_start_time, :utc_datetime, null: false
      add :encryption_key, :text, null: false
      add :participants, {:array, :map}
    end
  end

  def down do
    drop table(:lol_active_games)
  end
end
