defmodule Lor.Repo.Migrations.UpdatePlayerAddRecordAttribute do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pro_players) do
      add :record, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:pro_players) do
      remove :record
    end
  end
end
