defmodule Lor.Repo.Migrations.UpdateMatchAddAssetsVersion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lol_matches) do
      add :assets_version, :text, null: true
    end

    execute "UPDATE lol_matches SET assets_version = '13.24.1'"

    alter table(:lol_matches) do
      modify :assets_version, :text, null: false
    end
  end

  def down do
    alter table(:lol_matches) do
      remove :assets_version
    end
  end
end
